# Generated by Django 5.2.6 on 2025-09-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='resultado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('classificacao', models.TextField()),
                ('resposta', models.TextField()),
            ],
        ),
    ]
