# Generated by Django 5.2.6 on 2026-01-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0002_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
